---
# code: language=ansible
# tasks file for autofs

- name: Install autofs
  become: true
  ansible.builtin.apt: 
    pkg: 
      - autofs
    update_cache: true

- name: Add mountpoints to master map
  become: true
  ansible.builtin.lineinfile:
    path: /etc/auto.master
    line: "\
      {{ box.folder | default('/mnt') }} /etc/autofs.{{ box.name | default(ix) }} \
      {{ box.options | default() }}"
  loop: "{{ boxes }}"
  loop_control:
    loop_var: box
    index_var: ix

- name: Setup mountpoint files
  become: true
  ansible.builtin.blockinfile:
    create: yes
    path: /etc/autofs.{{ box.name | default(ix) }}
    block: "{{ lookup('template', 'auto.template.j2') }}"
    marker: "# {mark} Mountpoints for {{ name }}"
  loop: "{{ boxes }}"
  loop_control:
    loop_var: box
    index_var: ix
  notify: Restart autofs service