---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: debian11-ansible:latest
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
